#!/usr/bin/env Rscript


# Set input parameters ----------------------------------------------------

## Assumptions: 
## 1) metadata has a columnd called 'WellCombo' with 
## well location written like 'A01'.
## 2) raw fluorescence data has 17 leading lines of comments (see line 36)
## 3) the first 8 samples (i.e. column 1) contain PicoGreen standards
## in the following order 1000, 100, 10, 1, 0, 0, 0, 0

suppressPackageStartupMessages(require(optparse))
option_list <- list(
  make_option(c("-i", "--input"),
              action="store",
              default=NA,      
              type='character', 
              help="Input csv file of picogreen raw data fluorescence, as generated by Thermocloud. REQUIRED."), 
  make_option(c("-m", "--metadata"),
              action="store",
              default=NA,      
              type='character',
              help="Input metadata file. Must have SampleID and well locations for everything except the internal stds. REQUIRED.")
  make_option(c("-o", "--output_name"),
              action="store",
              default=NA,      
              type='character',
              help="Input metadata file. Must have SampleID and well locations for everything except the internal stds. REQUIRED."))

  )

opt = parse_args(OptionParser(option_list=option_list))


# Import and clean raw fluorescence data ---------------------------------------------------


datafile     <- opt$input
metadatafile <- opt$metadata

# read, but skip first 17 lines, which are generated by thermocloud and are commented out
rawdata  <- read.csv(datafile, stringsAsFactors = F, skip = 17)
metadata <- read.csv(metadatafile,stringsAsFactors = F, header = T)

# select and rename columns
rawdata           <- rawdata[1:3]
colnames(rawdata) <- c("well","cycle","fluorescence")

## Fix well syntax

## Separate row letter
row_letter <- substring(rawdata$well,1,1)

## Add leading zeroes to single digit numbers
col_number <- as.integer(substring(rawdata$well,2,3))
col_number <- formatC(col_number, width = 2, format = "d", flag = "0")

## Paste back together and update data
rawdata$col_number <- col_number
rawdata$row_letter <- row_letter
rawdata$well       <- paste(row_letter,col_number, sep="")
rawdata            <- rawdata[order(rawdata$well),]


## Create data frames for calculations
## separate data frame by cycle

cycle1 <- rawdata[rawdata$cycle==1,]
cycle2 <- rawdata[rawdata$cycle==2,]


# Calculate standard curve based on fluorescence of internal stand --------


## Subtract fluorescence of cycle 1 from fluorescence of cycle 2 
adj_fluor <- cycle2$fluorescence - cycle1$fluorescence

## create data frame of all adjusted fluorescence readings, excluding standards
new.data <- data.frame(adj_fluor = adj_fluor, well= cycle1$well, logFluor=log10(adj_fluor))

## Define concentration of standards and create data frame of standard concentrations and standard fluorescence
standards <- new.data[grep("^.01", new.data$well),] 
standards$concentrations <- c(1000,100,10,1,0,0,0,0)

## log transform
standards$logConc  <- log10(standards$concentrations)
standards$logFluor[standards$concentrations <= 0] <-NA

# ## Generate linear equation based on log transformed readings from standards
standardcurve <- lm( logConc ~ logFluor, data = standards )

## predict concentrations for real samples
new.data$predicted_concentrations <- 10^(new.data$logFluor*coef(standardcurve)[2]+coef(standardcurve)[1])

plot(log10(standards$concentrations),log10(standards$adj_fluor))

## write to csv using set name
write.csv(new.data[c(2,1,4)], "data.pico_green_quant.csv")

## Generate histogram of concentrations < 300 ng / ul
quants <- new.data[[4]]
quants <- quants[quants < 300]
hist(quants,breaks = 60)


# Generate final table of metadata and calculated DNA concentrations --------

## merge metadata and fluorescence based on well location
full.data <- merge(new.data, metadata, by.x = "well", by.y = "WellCombo")
full.data$logConcentration <- log10(full.data$predicted_concentrations)

## Change metadata for wells containing a quantification standard
full.data[grep("^.01", full.data$well),9:ncol(full.data)] <- "Std"

##write out csv
write.csv(full.data, paste(output_name,"fulldata.pico_green_quant.csv"), row.names = F)